name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test Docker Image
        run: |
          docker build -t docker-app .
          docker run docker-app pytest
          exit_code=$?

      - name: Commit changes
        if: ${{ job.steps[2].outcome == 'success' && steps.build-and-test.outputs.exit_code == 0 }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Test passed, commit changes"
          git push
