name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test Docker Image
        run: |
          docker build -t docker-app.
          docker run docker-app pytest

      - name: Check pytest exit code
        id: pytest-check
        run: exit $?

      - name: Commit changes
        if: ${{ steps.pytest-check.outcome == 'success' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Test results: ${{ steps.pytest-check.outcome }}"
          git push
