name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test Docker Image
        run: |
          docker build -t docker-app .
          docker run docker-app pytest
          exit_code=$?

      - name: Revert commit if pytest fails
        if: ${{ job.steps[2].outcome == 'failure' }}
        run: |
          git revert --no-edit HEAD~1
          git push